name: face_swap
description: AI换图 - 智能AI换脸应用
publish_to: 'none'
version: 1.5.9+48

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.9.2
  provider: ^6.1.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0
  cached_network_image: ^3.3.0
  photo_view: ^0.15.0
  fluttertoast: ^8.2.0
  shimmer: ^3.0.0
  image_gallery_saver_plus: ^4.0.1
  path_provider: ^2.1.5
  video_player: ^2.8.0
  package_info_plus: ^8.0.0
  flutter_sticky_header: ^0.6.5
  share_plus: ^10.0.0
  sign_in_with_apple: ^6.1.0
  in_app_purchase: ^3.1.0
  net_layer:
    path: ../packages/net_layer
  auth_suite:
    path: ../packages/auth_suite
  iap_suite:
    path: ../packages/iap_suite

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
